### ISSUE TITLE
Missing cities_coords.csv file

### ISSUE THREAD

**Issue by Nikkofv** [rmkujala/d4dttimes#1]
Hello Rainer Kujala,

It was great meeting you at the NetMob conference.  It is always exciting to meet like minds in the field.  Thank you for letting me know about the google distancematrix api, I will make sure to utilize that.  By the way, I wanted to check out your posted example code and noticed that you did not include your cities_coords.csv file.  Which cities of Senegal did you use?  I appreciate you taking the time. 

Thank you,
Nicholas "Nikko" Vogel

**Comment by rmkujala** [comment]
Hi Nikko, 

See the sample_cities.csv for an example.

We took the city coordinates from 
http://www.tageo.com/index-e-sg-cities-SN.htm

I will add the properly formatted city csv file here next.

**Comment by rmkujala** [comment]
I now added cities_coords_senegal.csv for convenience in 39f04c3

(Or actually, it is more of a tsv file but nevertheless.)

**Comment by Nikkofv** [comment]
Hey Rainer,

I will try it out again.  Also yes, I would love to take a look at the
python code you wrote to facilitate the use of the Google distance matrix
API.

Thank you,
-Nikko

**Comment by rmkujala** [comment]
Nikko, have a look at:

https://gist.github.com/rmkujala/af08356588d63e3137a8
